#---
spring:
  application:
    name: spring-cloud-eureka
  #profiles: peer1
server:
  port: 8087
eureka:
  instance:
    hostname: localhost
    # hostname: peer1
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 启动 http://localhost:8087/
#      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: peer
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/