spring:
  application:
    name: spring-cloud-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8087/eureka/
server:
  port: 8083
feign:
  hystrix:
    enabled: true

#logging:
#  level:
#    ROOT: INFO
#    org.springframework.web: WARN
#    com.shangchao.pmscloud.wx: DEBUG
#    org.mongodb.driver: INFO